# Generated by Django 6.0.5 on 2026-05-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='parent_relationship',
        ),
    ]
